[package]
name = "app_route_derive"
version = "0.1.0"
authors = ["Brian Schwind <brianmschwind@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15", features = ["extra-traits"] }
proc-macro2 = "0.4.28"
quote = "0.6.12"
regex = "1.1.6"
